### ISSUE TITLE
[request] please update package on npm

### ISSUE THREAD

**Issue by 9bow** [xissy/node-mecab-ffi#11]
Hi, [the latest commit](https://github.com/xissy/node-mecab-ffi/commit/19671bff4da62bd11d96ec5b3ce1f3019f6392e8) does not released on npm.

So please check it.

Thanks.

**Comment by 9bow** [comment]
...and please also check the lastest commit did right.

Refer to [the mecab-ko-dic tag description](https://docs.google.com/spreadsheets/d/1-9blXKjtjeKZqsf4NzHeYJCrr49-nXeRF6D80udfcwY/edit#gid=589544265), the 'NN' changed to 'NNG' and 'NNP'.

It does NOT include 'NNB', 'NR' and 'NP'.

**Comment by xissy** [comment]
Hi @9bow,
I have been busy so that I cannot make time to work for this repository so far. Can you please check the latest commit in your local machine and let me know whether it is okay or not? Will do release your commit into npm after that, immediately. Thank you.

**Comment by 9bow** [comment]
Sorry for late, I have been busy so that cannot follow up this issue.

The version number of [mecab-ffi on npm](https://www.npmjs.com/package/mecab-ffi) is same with this (github's) one(0.1.0),
but the noun codes are not updated. (Using only NN instead of NNG or NNP, outdated.)

So please update any version of this github codes(I prefer #12 one) to npm's, and version number, too.

Thanks.

**Comment by xissy** [comment]
Thank you very much, @9bow. I have updated the npm module with yours.
