### ISSUE TITLE
The most of API's are not working

### ISSUE THREAD

**Issue by wodory** [xissy/node-mecab-ffi#5]
I installed the package, I cannot use mecab on node. I must install mecab-ko and mecab-ko-dic manually. 

Even I installed the mecab library manually, most of APIs are not working like 'extractNouns' becuase the type code is changed in new version of mecab. 

In this code, use the noun code 'NN', however, the noun code are several type likes 'NNP', 'NNG' and so on. 

I guess xissy don't review the problem. If somebody has same problem, you just modify the file, 'index.coffee'.

**Comment by xissy** [comment]
@wodory Sorry I moved my job to a kind of big company so couldn't make a time to take care of my ope repositories. Why don't you send me a pull request please? Thanks. :)

**Comment by wodory** [comment]
Ooops! I'm very surprised to your reply. I guess you don't read the issue or push request LOL. As you said, I'll send a full request with additional information about Mac OS. Thank you for great porting!

**Comment by xissy** [comment]
Thanks for your pull request. #6
